stages:
  - package
 

package:
  stage: package
  tags:
    - ahmad 
  script:
    - echo "Packaging Maven Project"
    - chmod +x app-version.sh
    - ./app-version.sh
    - mvn clean package
  artifacts:
    paths:
      - target/*.jar