stages:
  - package
 
build_jar:
  stage: package
  tags:
    - osama
  script:
    - echo "Packaging Maven Project"
    - chmod +x set-version.sh
    - ./set-version.sh
    - mvn clean package
  artifacts:
    paths:
      - target/*.jar