stages:
  - package

package:
  stage: package
  tags:
    - Ahmad   
  script:
    - COMMIT_DATE=$(git show -s --format=%cd --date=format:%y%m%d $CI_COMMIT_SHA)
    - SHORT_SHA=${CI_COMMIT_SHORT_SHA}
    - NEW_VERSION="${COMMIT_DATE}-${SHORT_SHA}"
    - echo "Packaging version: $NEW_VERSION"
    - mvn clean package
    - mv target/*.jar target/myapp-$NEW_VERSION.jar
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 day
  only:
    - branches
