apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "progressoft-app.fullname" . }}-config
data:
  SPRING_PROFILES_ACTIVE: "default"
  SPRING_DATASOURCE_URL: "jdbc:mysql://{{ .Release.Name }}-progressoft-app-mysql:3306/assignment?allowPublicKeyRetrieval=true&useSSL=false"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "com.mysql.cj.jdbc.Driver"
  SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: "org.hibernate.dialect.MySQL8Dialect"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "progressoft-app.fullname" . }}-check-db
data:
  wait-for-mysql.sh: |
    #!/bin/sh
    RETRIES=30
    until mysql -h {{ .Release.Name }}-progressoft-app-mysql -u $MYSQL_USER -p$MYSQL_PASSWORD -e "SELECT 1" > /dev/null 2>&1 || [ $RETRIES -eq 0 ]; do
      echo "Waiting for MySQL... $((RETRIES--))"
      sleep 5
    done

    if [ $RETRIES -eq 0 ]; then
      echo "MySQL not ready after 30 tries"
      exit 1
    fi
    echo "MySQL is up"
