apiVersion: v1
kind: Service
metadata:
  name: {{ include "progressoft-app.fullname" . }}-mysql
  labels:
    app: mysql
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql
  type: ClusterIP
