apiVersion: v1
kind: Secret
metadata:
  name: {{ include "progressoft-app.fullname" . }}-mysql-secret
type: Opaque
data:
  username: {{ .Values.mysql.auth.username | b64enc }}
  password: {{ .Values.mysql.auth.password | b64enc }}
  root-password: {{ .Values.mysql.auth.rootPassword | b64enc }}
