apiVersion: apps/v1
kind: Deployment
metadata:
  name: assignment-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assignment-app
  template:
    metadata:
      labels:
        app: assignment-app
    spec:
      imagePullSecrets:
      - name: regcred
      initContainers:
      - name: check-db
        image: mysql:8
        command: [ "sh", "-c", "/scripts/wait-for-mysql.sh" ]
        volumeMounts:
        - name: scripts
          mountPath: /scripts
        env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password

      containers:
      - name: app
        image: ps95adagher/assignment:250601-391af902
        ports:
        - containerPort: 8090
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "default"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql:3306/assignment?allowPublicKeyRetrieval=true&useSSL=false"
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
          value: "com.mysql.cj.jdbc.Driver"
        - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
          value: "org.hibernate.dialect.MySQL8Dialect"
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: "update"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8090
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8090
          initialDelaySeconds: 15
          periodSeconds: 5
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
      volumes:
      - name: scripts
        configMap:
          name: check-db
          defaultMode: 0755

---
apiVersion: v1
kind: Service
metadata:
  name: assignment-service    
spec:
  selector:
    app: assignment-app
  ports:
    - port: 80
      targetPort: 8090
  type: NodePort