apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: assignment-app-monitor
  namespace: monitoring
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: assignment-app 
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
